# Generated by Django 3.2.6 on 2021-10-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHome',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('titl1', models.CharField(max_length=200)),
                ('content1', models.TextField()),
                ('note', models.TextField()),
                ('titl2', models.CharField(max_length=200)),
                ('content2', models.TextField()),
                ('slug', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('time', models.DateField(auto_now_add=True)),
                ('tags1', models.CharField(max_length=50)),
                ('tags2', models.CharField(max_length=50)),
            ],
        ),
    ]
