# Generated by Django 3.2.6 on 2021-10-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloghome',
            old_name='titl1',
            new_name='title1',
        ),
        migrations.RenameField(
            model_name='bloghome',
            old_name='titl2',
            new_name='title2',
        ),
    ]
