# Generated by Django 3.2.6 on 2021-10-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20211030_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogHome',
            new_name='Blog',
        ),
    ]
