# Generated by Django 3.2.6 on 2021-10-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_bloghome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogHome',
        ),
    ]
